### ISSUE TITLE
How to install nix-bisect?

### ISSUE THREAD

**Issue by das-g** [timokau/nix-bisect#10]
How does one make nix-bisect available for usage? It seems to be neither in NixPkgs nor on PyPI. I also didn't find any build instructions.

At least one method should be covered in `README.md`.

**Comment by timokau** [comment]
It is kind of documented in the README, the very last part:

>Keep in mind however that this is very early stages. Barely anything is documented. I built this to scratch my own itch, and I continue developing it whenever I need some feature.
>
> Still, I can already be quite useful for some people. It is not packaged in nixpkgs, but if you want to try it out simply use nix-shell with the default.nix provided in this repository.

I basically develop this whenever I have a need for it. Turns out waiting for a bisect run to complete is a great time to develop the bisect tooling. That hasn't happened for a while (in addition to many other things going on), therefore development has been kind of dormant. Bugs should be expected (and reports are welcome, but may not be dealt with by me in a timely manner).
