### ISSUE TITLE
Add nix-bisect to nixpkgs

### ISSUE THREAD

**Issue by turion** [timokau/nix-bisect#21]
Probably most users of `nix-bisect` install software from nixpkgs. It would be great if one could install `nix-bisect` from there as well.

(Alternative: Add a `flake.nix` to your project that describes how to build it.)

**Comment by timokau** [comment]
This has recently been done: https://github.com/NixOS/nixpkgs/pull/167326

Though I wouldn't have done it myself, since I'm not committed to the level of maintenance that this might suggest. `nix-bisect` still has plenty of kinks, and I haven't worked on them in a while. I mostly develop it on an as-needed basis. Also see [this post](https://github.com/NixOS/nixpkgs/pull/167326).

The package seems relatively popular in the community and my current commitment probably doesn't do it justice. A fork from a community member that has a bit more time to dedicate to it would be welcome.
